service: serverlessProject

provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  region: ap-southeast-1
  environment:
    tableName1: ${self:custom.usersTableName}
    tableName2: ${self:custom.emojiTableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"

custom:
  usersTableName: WebsocketUsers
  emojiTableName: EmojiTable

functions:
  websocket-connect:
    handler: lambdas/websockets/connect.handler
    events:
      - websocket:
          route: $connect
  websocket-disconnect:
    handler: lambdas/websockets/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  websocket-broadcast:
    handler: lambdas/websockets/broadcast.handler
    events:
      - websocket:
          route: broadcast
  websocket-default:
    handler: lambdas/websockets/default.handler
    events:
      - websocket:
          route: $default
  websocket-message:
    handler: lambdas/websockets/message.handler
    events:
      - websocket:
          route: message

resources:
  Resources:
    WebsocketUserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usersTableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    WebsocketEmojiTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.emojiTableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
